[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = [
    "forge-std/=lib/forge-std/src/",
    "v2-core/=lib/v2-core/",
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "v2-periphery/=lib/v2-periphery/",
    "1inch-v2-contracts/=lib/1inch-v2-contracts/"
]
